= Welcome to the PULSE-A Project Docs

This is the primary documentation site for the project. Navigate using the sidebar on the left to see all pages.

All mission-level systems engineering documentation and subsystem design motivation live in this repository.

To view component-level hardware documentation and detailed firmware documentation (including how to run our code), navigate to the relevant documentation using the button in the bottom left of this window.

== GitHub Navigation

The UCSP GitHub project is the home for this documentation and for all of our repositories. The project can be accessed link:https://github.com/UChicago-PULSE[here].

Within the project, there are several important repositories to note. The link:https://github.com/UChicago-PULSE/mission-documentation[mission-documentation repository], where this documentation lives, also houses PULSE-A's design review slideshows (SRR and PDR, and soon-to-be CDR), quarterly updates, and publications. 

The link:https://github.com/UChicago-PULSE/pulse-hardware[pulse-hardware repository] houses CAD files for all student-designed hardware on the spacecraft (in both .step and .f3d format). Electronic design files (in KiCAD format) are also located here.

The link:https://github.com/UChicago-PULSE/pulse-firmware[pulse-firmware repository] houses the C files for our FSW.

== Reference Information

For definitions, acronyms, and Capitalization used throughout the PULSE-A documentation, see the link:general/reference_list.html[Reference List] page.

