= Welcome to the PULSE-A Project Docs

This is the primary documentation site for the project. Navigate using the sidebar on the left to see all pages.

All mission-level systems engineering documentation and subsystem design motivation live in this repository.

To view component-level hardware documentation and detailed firmware documentation (including how to run our code), navigate to the relevant documentation using the button in the bottom left of this window.

== GitHub Navigation

The UCSP GitHub project is the home for this documentation and for all of our repositories. The project can be accessed link:https://github.com/UChicago-PULSE[here].

Within the project, there are several important repositories to note. The link:https://github.com/UChicago-PULSE/mission-documentation[mission-documentation repository], where this documentation lives, also houses PULSE-A's design review slideshows (SRR and PDR, and soon-to-be CDR), quarterly updates, and publications. 

The link:https://github.com/UChicago-PULSE/pulse-hardware[pulse-hardware repository] houses CAD files for all student-designed hardware on the spacecraft (in both .step and .f3d format). Electronic design files (in KiCAD format) are also located here.

The link:https://github.com/UChicago-PULSE/pulse-firmware[pulse-firmware repository] houses the C files for our FSW.


== Reference Information

These lists contains definitions, acronyms, and formatting guidelines that are used throughout the PULSE-A documentation.

=== Definitions

* **Payload Computer** – Beaglebone component of payload controller
* **Payload Controller** – Board consisting of the payload computer and payload FPGA
* **Payload Transmission Laser** (or just Transmission Laser after being introduced) – 1550 nm downlink data laser
* **Payload Beacon Laser** – 638 nm laser aligned to the satellite's body pointing
* **Optical Ground Station (OGS) Beacon Laser** – 1064 nm laser aligned to the OGS telescope

=== Acronyms

* **ADCS** – Attitude Determination and Control System
* **AFT** – Allowable Flight Temperature
* **AIT** – Assembly, Integration and Testing
* **APD** – Avalanche Photodiode
* **I^2^C** – Inter-Integrated Circuit
* **CAN** – Controller Area Network
* **CDH** – Command and Data Handling
* **CDR** – Critical Design Review
* **cFS** – Core Flight System
* **COTS** – Commercial Off-The-Shelf
* **CPolSK** – Circular Polarization Shift Keying
* **CSLI** – CubeSat Launch Initiative
* **CSP** – Cubesat Space Protocol
* **CSS** – Coarse Sun Sensor
* **CTE** – Coefficient of Thermal Expansion
* **DNE** – Do Not Exceed
* **EDFA** – Erbium-Doped Fiber Amplifier
* **EMI** – Electromagnetic Interference (Testing)
* **EPS** – Electrical Power System
* **FAA** – Federal Aviation Administration
* **FCC** – Federal Communications Commission
* **FPGA** – Field-programmable Gate Array
* **FRR** – Flight Readiness Review
* **FSM** – Fast (or Fine) Steering Mirror
* **FSS** – Fine Sun Sensor
* **GEO** – Geosynchronous Equatorial Orbit
* **GFSK** – Gaussian Frequency-Shift Keying
* **HWP** – Half-Wave Plate (or Half Waveplate)
* **IARU** – International Amateur Radio Union
* **ITU** – International Telecommunication Union
* **LD** – Laser Diode
* **LEO** – Low Earth Orbit
* **MEMS** – Micro-electromechanical System(s)
* **MOI** – Moment of Inertia
* **MPE** – Maximum Predicted Environment
* **NASA** – National Aeronautics and Space Administration
* **OBC** – On-Board Computer
* **OGS** – Optical Ground Station
* **PAT** – Pointing, Acquisition and Tracking
* **PD** – Photodiode
* **PDR** – Preliminary Design Review
* **PDU** – Power Distribution Unit
* **PPM** – Pulse Position Modulation
* **PPRR** – Pre-Procurement Readiness Review
* **PULSE-A** – Polarization-modUlated Laser Satellite Experiment
* **QKD** – Quantum Key Distribution
* **QPD** – Quadrant Photodiode (Quad cell, four quadrant diode, etc.)
* **QWP** – Quarter-Wave Plate (or Quarter Waveplate)
* **RFGS** – Radio Frequency Ground Station
* **SNR** – Signal to Noise Ratio
* **SRR** – System Requirements Review
* **STK** – Systems Tool Kit
* **TCP** – Transmission Control Protocol
* **TRR** – Test Readiness Review
* **TVAC** – Thermal Vacuum Chamber
* **V&V** – Verification and Validation

=== Capitalization

* **Spacemanic**
* **Beaglebone Black**
* **CubeSat**
* **GOMspace**
