= RF Ground Station Documentation

The RF communications subsystem is designed to communicate between the PULSE-A CubeSat and our ground station. The RF ground station (RFGS) will communicate with a satellite radio module to transmit frequent health beacon and GPS data to and send commands to enable the laser communication demonstration. The RFGS is intended to be used primarily for PULSE-A, but is designed with the intention to be flexible and used for future CubeSat missions and collaborations.

We plan to operate in the UHF amateur band (435-438 MHz), common for university CubeSat missions. We choose UHF because it's bandwidth (transmission rate) matches our requirements for how quickly data needs to be transmitted. VHF has similar capabilites. We will transmit at half-duplex, where all communications occur over one frequency and you can either transmit and receive at one time. However, many hardware choices will be compatible with full-duplex in case future University of Chicago CubeSat missions require it.

At our transmission rate of 9600bps, we can send critical GPS data during our laser aquisition sequence every ~0.25 seconds.


The following is a block diagram for the RFGS.

image::rfgs-diagram.svg[]

== Licensing
To transmit over radio frequencies, licensing from the FCC is required. We plan to coordinate with the IARU, then FCC, then ITU, to obtain experimental and amateur licenses. During design and development of the RF subsystem, members of the PULSE-A team will become familiar with amateur radio equipment and uses and obtain ham amateur licenses which will be needed to transmit to the CubeSat.

To see more about PULSE-A's licensing, refer to xref:licensing.adoc[our licensing documentation].

== Hardware

During viable radio passes the RFGS will communicate with the SpaceManic Murgas satellite radio module, receiving telemetry and sending commands for future passes.

The RFGS will use a Cross-Yagi antenna for its high gain and ease of use, which will be connected to a roof mount with a Yaesu G-5500 rotator controlled by the CSN Technologies Self-contained Antenna Tracker and GPredict. The uplink and downlink will be supported by the ICOM-9700 transceiver, with a SSB SP70 masthead preamplifier connected to a DCW 2004 B power coupler to boost weak signals from the satellite. The Cross-Yagi antenna will transmit right-handed circularly polarized RF signals at 30 Watts and receive linearly polarized RF signals from the satellite. While this polarization mismatch will decrease the strength of the received signal by approximately 3 dB, the combination of circular transmission and linear reception will ensure reliable signal reception from the satellite regardless of its orientation.

== RF Link

All commands to the CubeSat will be encrypted to ensure operational integrity, all telemetry will be unencrypted so that other amateur radio operators can receive and decode. We plan to send around-the-world telemetry and participate in the SatNOGS ground network. Other than during RFGS viables radio passes, the AX.25 digipeater will be available for amateur operators.


The RFGS will receive telemetry and sending commands and files using the AX.25 standard amateur radio frames encapsulating CubeSpace Protocol packets over KISS protocol, which will wrap CubeSat Space Protocol (CSP) packets containing command and telemetry data. It will receive and transmit at 9600 baud using GFSK/GMSK(TBD) modulation. Packets will be decoded using a terminal node controller (TNC) and a ground station computer.

To see more about the RFGS software, refer to xref:rfgs-software.adoc[our software documentation].

== RFGS Location

We intend to deploy the RFGS on the roof of the Knapp Center for Biomedical Discovery at the University of Chicago. This location will give the antenna an unobstructed line-of-sight for the satellite’s orbit. This location will enable the RFGS to connect with the satellite at an elevation of less than 5 degrees, allowing the RFGS to initiate the pointing, acquisition, and tracking (PAT) sequence before the satellite is high enough to begin optical transmission.
