= GPS Position Manager Application

== Overview

The GPS Position Manager Application is an OBC default application that interfaces with the GNSS receiver to track satellite position and notifies other applications as the vehicle reaches ground-station overpasses.

== Data Input

* Reads application configuration table
* Receives data from Communication App designated as originating from GPS module
* Accepts input from the limit checker application in case of a detected fault

== Data Output

* Sends command structs to the Communication App with instructions to package as CSP and send to GPS module
* Publishes GPS data on GPS topic

== Data Processing

* Builds GPS command structs
* Monitors the current satellite velocity and position data output by the ADCS, performing common transformations on the data

== Integration Points

* xref:communication-manager-app.adoc[Communication Manager Application]: Sends GPS commands and receives GPS module data
* xref:limit-checker-app.adoc[Limit Checker Application]: Receives fault notifications
* **Software Bus**: Publishes GPS topic data
