name: Trigger webhook to rebuild
on:
  push:
    branches: [main]
permissions:
  contents: read
  actions: write
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ context.repo.owner }}/docs-site/dispatches \
            -d '{"event_type":"trigger-rebuild"}'
