name: Trigger webhook to rebuild
on:
  push:
    branches: [main]
permissions:
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to rebuild
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: "docs-site",
              event_type: "trigger-rebuild"
            });
